-- Create PRODUCTS table
CREATE TABLE PRODUCTS (
  pro_id INT PRIMARY KEY,
  pro_name VARCHAR(50),
  Pro_Price INT,
  Supplier_id INT
);

-- Insert rows into PRODUCTS table
INSERT INTO PRODUCTS VALUES (1, 'Mouse', 100, 2);
INSERT INTO PRODUCTS VALUES (2, 'Keyboard', 150, 1);
INSERT INTO PRODUCTS VALUES (3, 'HHD', 1000, 4);
INSERT INTO PRODUCTS VALUES (4, 'Mouse', 200, 1);
INSERT INTO PRODUCTS VALUES (5, 'Keyboard', 100, 2);
INSERT INTO PRODUCTS VALUES (6, 'Mouse', 150, 3);


-- Create SUPPLIER table
CREATE TABLE SUPPLIER (
  Supplier_id INT PRIMARY KEY,
  Supplier_name VARCHAR(50)
);

-- Insert rows into SUPPLIER table
INSERT INTO SUPPLIER VALUES (1, 'DELL');
INSERT INTO SUPPLIER VALUES (2, 'Lenovo');
INSERT INTO SUPPLIER VALUES (3, 'HP');
INSERT INTO SUPPLIER VALUES (4, 'Amazon');


-- Q1. Inner Join
SELECT *
FROM PRODUCTS 
INNER JOIN SUPPLIER ON PRODUCTS.Supplier_id = SUPPLIER.Supplier_id;

-- Q2. Equi Join
SELECT PRODUCTS.PRO_ID, PRODUCTS.PRO_NAME, PRODUCTS.PRO_PRICE, SUPPLIER.SUPPLIER_NAME
FROM PRODUCTS, SUPPLIER
WHERE PRODUCTS.Supplier_id = SUPPLIER.Supplier_id;

-- Q3. Natural Join
SELECT *
FROM PRODUCTS
NATURAL JOIN SUPPLIER;

-- Q4. Cross Join (Cartesian product)
SELECT *
FROM PRODUCTS
CROSS JOIN SUPPLIER;

-- Q5A. Left Outer Join
SELECT *
FROM PRODUCTS
LEFT OUTER JOIN SUPPLIER ON PRODUCTS.Pro_Price =  50*SUPPLIER.Supplier_id;

-- SELECT *
-- FROM PRODUCTS
-- LEFT OUTER JOIN SUPPLIER ON PRODUCTS.Supplier_id = SUPPLIER.Supplier_id;

-- Q5B. Right Outer Join
SELECT *
FROM PRODUCTS
RIGHT OUTER JOIN SUPPLIER ON PRODUCTS.Supplier_id = SUPPLIER.Supplier_id-1;

-- SELECT *
-- FROM PRODUCTS
-- RIGHT OUTER JOIN SUPPLIER ON PRODUCTS.Supplier_id = SUPPLIER.Supplier_id;

-- Q5C. Full Outer Join
SELECT *
FROM PRODUCTS
FULL OUTER JOIN SUPPLIER ON PRODUCTS.Supplier_id+1 = SUPPLIER.Supplier_id;

-- SELECT *
-- FROM PRODUCTS
-- FULL OUTER JOIN SUPPLIER ON PRODUCTS.Supplier_id = SUPPLIER.Supplier_id;
