DROP TABLE STUD;

CREATE TABLE STUD (
    ID INT PRIMARY KEY,
    NAME VARCHAR2(20)
);

-- Simple trigger
CREATE OR REPLACE TRIGGER PRINT_HELLO
BEFORE INSERT ON STUD
BEGIN
	DBMS_OUTPUT.PUT_LINE('HELLO');
END;
/

INSERT INTO STUD VALUES(1, 'ABC');
INSERT INTO STUD VALUES(2, 'DEF');
INSERT INTO STUD VALUES(3, 'GHI');

-- Trigger 1 (UPDATE trigger)
CREATE OR REPLACE TRIGGER STARTS_WITH_X
BEFORE UPDATE ON STUD
FOR EACH ROW
WHEN (NEW.NAME LIKE 'X%')
DECLARE
    NEW_NAME STUD.NAME%TYPE;
BEGIN
    NEW_NAME := :NEW.NAME;
	DBMS_OUTPUT.PUT_LINE('NAME STARTS WITH X: ' || NEW_NAME);
END;
/


UPDATE STUD
SET NAME='XYZ'
WHERE ID=3;

CREATE OR REPLACE VIEW STUD_VIEW AS
SELECT * FROM STUD;

-- Trigger 2 (INSTEAD OF trigger, ONLY ALLOWED ON VIEWS)
CREATE OR REPLACE TRIGGER STUD_VIEW_insert
INSTEAD OF INSERT ON STUD_VIEW
BEGIN
    INSERT INTO STUD VALUES(:NEW.ID, :NEW.NAME);
	DBMS_OUTPUT.PUT_LINE('Inserted into STUD');
END;
/

INSERT INTO STUD_VIEW VALUES(5, 'JKL');