DROP TABLE STUD;

CREATE TABLE STUD (
    ID INT,
    NAME VARCHAR2(20),
    COST INT,
    PRIMARY KEY(ID, NAME, COST)
);

INSERT INTO STUD VALUES(1, 'ABC', 20);
INSERT INTO STUD VALUES(1, 'ABC', 30);
INSERT INTO STUD VALUES(3, 'DEF', 40);
INSERT INTO STUD VALUES(4, 'GHI', 60);

SELECT ID, NAME, SUM(COST)
FROM STUD
GROUP BY ID, NAME;
